### ISSUE TITLE
Outlook Device Policy Broken in 2.25

### ISSUE THREAD

**Issue by ThatJeffGuy** [Xposed-Modules-Repo/com.darkeyes.tricks#1]
Hello!

Installed the latest release, rebooted, activated the feature, rebooted again. Removed app from device admin section, opened Outlook, prompt to remove account or make it admin app.

Figured it was some caching thing, so I removed the account and cleared cache on Outlook app, and attempted to re-add, but it asks for admin policy still.

Pixel 6 non pro running one month behind on security patches, latest lsposed and Magisk as of post time. Latest app version on play store as well.

Let me know which logs are helpful and I'll attach.

**Comment by ThatJeffGuy** [comment]
As of 2.26 this is still an issue

**Comment by darkeyes84** [comment]
Fixed
